### ISSUE TITLE
Error enrolling certificate

### ISSUE THREAD

**Issue by defacto64** [visual-est/visual-est-public#8]
Hello,

we are testing VisualEST with our EST Server, and we get a strange error, shown below. The same error does **NOT** occur when calling /simpleenroll via curl or wget, with exactly the same input parameters (CSR, username and password). What can be the cause of this error? Please, advise.

```
Time: 16:00:07.614881900
Level: ERROR
Component: Visual EST

Unable to perform certificate enrollment. 
Stream closed before limit fully read, Read: 0 ContentLength: 22 HTTP Status Code: 0
com.vest.visualest.exception.CertificateEnrollmentException: 
Stream closed before limit fully read, Read: 0 ContentLength: 22 HTTP Status Code: 0
	at com.vest.visualest.client.VisualEstClient.enrollCertificateOperation(VisualEstClient.java:277)
	at com.vest.visualest.task.RequestCertificateEnrollmentTask.call(RequestCertificateEnrollmentTask.java:20)
	at com.vest.visualest.task.RequestCertificateEnrollmentTask.call(RequestCertificateEnrollmentTask.java:6)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.bouncycastle.est.ESTException: Stream closed before limit fully read, Read: 0 ContentLength: 22 HTTP Status Code: 0
	at org.bouncycastle.est.ESTService.simpleEnroll(Unknown Source)
	at com.vest.visualest.client.VisualEstClient.enrollCertificateOperation(VisualEstClient.java:252)
	... 7 more
Caused by: java.io.IOException: Stream closed before limit fully read, Read: 0 ContentLength: 22
	at org.bouncycastle.est.ESTResponse$2.close(Unknown Source)
	at org.bouncycastle.est.ESTResponse.close(Unknown Source)
	at org.bouncycastle.est.HttpAuth$1.hijack(Unknown Source)
	at org.bouncycastle.est.jcajce.DefaultESTClient.performRequest(Unknown Source)
	at org.bouncycastle.est.jcajce.DefaultESTClient.doRequest(Unknown Source)
	... 9 more

```

**Comment by visual-est** [comment]
Hi @defacto64 . The stack trace above shows some issue with Bouncy Castle/Java. I have release a newer version where the latest versions of BC and Java are used. Do you mind to try with this new version? If you still see an issue, is your EST server exposed so I can use it?

https://github.com/visual-est/visual-est-public/releases/tag/1.0.115

**Comment by defacto64** [comment]
Hi, thank you very much for your attention and for the update. 
Unfortunately, with version 1.0.115 nothing changes: I get exactly the same exception in the log upon calling /simpleenroll.
I am sorry that you cannot talk to our EST Server as it's not exposed, and we would not be able to have it exposed in a short time.
I can only add that calling our EST Server with cURL or wget or libest works fine....
Let me know if you need any additional information...

**Comment by visual-est** [comment]
@defacto64 The error comes from Bouncy Castle, so most probably you will have compatibility issues with other applications that are using the EST client of BC. 

My speculation is that the value of the Content-Length header is wrong. The EST logic reads the response according to the value of Content-Length header (I assume that cURL does not do that).

It is better to check if the Content-Length value is same as the size of the response.

**Comment by defacto64** [comment]
We are positive that the Content-Length value is same as the size of the response, we have just re-checked that.

**Comment by visual-est** [comment]
@defacto64 Thanks for checking. If you still want to troubleshoot it, you can try the CLI tool of BC (see below). If possible, can you capture the HTTP traffic and post it here?

https://github.com/bcgit/bc-java/tree/master/test/est/example

**Comment by visual-est** [comment]
Closing this due to lack of response. Will open if needed. The issue is in either the EST server or the EST Bouncy Castle library (highly unusual).
